package com.aioldsweb.www.model.enums;

public enum SubjectEnum {

    RESTAURANT_MANAGEMENT_SYSTEM,
    HOTEL_MANAGEMENT_SYSTEM,
    ECOMMERCE_PLATFORM,
    EDUCATIONAL_INSTITUTION_WEBSITE,
    HEALTHCARE_MANAGEMENT_SYSTEM,
    FINANCIAL_SERVICES_WEBSITE,
    REAL_ESTATE_MANAGEMENT_SYSTEM,
    TRAVEL_AND_TOURISM_PLATFORM,
    FITNESS_CENTER_MANAGEMENT_SYSTEM,
    LEGAL_SERVICES_WEBSITE,
    AUTOMOTIVE_INDUSTRY_SOLUTIONS,
    EVENT_MANAGEMENT_PLATFORM,
    BEAUTY_SALON_AND_SPA_MANAGEMENT_SYSTEM,
    CONSTRUCTION_INDUSTRY_SOLUTIONS,
    TECHNOLOGY_AND_IT_SERVICES_WEBSITE,
    OTHER
}
